# https://starship.rs/config

command_timeout = 700 # default: 500

[character]
success_symbol = '[🦄](bold green)'
error_symbol = '[🙊](bold red)'

[container]
style = 'bold blue dimmed'
format = '($style)'

[custom.container_name]
command = "container_name"
when = "container_name"
symbol = '🫙'
style = 'bold blue dimmed'
format = "[$symbol $output]($style) "

[shell]
disabled = true
fish_indicator = '🐡'
nu_indicator = '🦀'
zsh_indicator = '🦪'
bash_indicator = '🐚'
unknown_indicator = 'mystery shell'
